# Based on https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
# Following instructions from https://github.com/quarto-dev/quarto-actions/tree/main/publish#github-pages
# For details on the syntax of this file, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches: main

name: Build and publish to GitHub Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # Permissions required to publish to GitHub Pages
    permissions:
      contents: write
      pages: write

    steps:
      - name: Fetch repository contents
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render site and publish it to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This secret is always available for GitHub Actions
